#!/usr/bin/env sh

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex='^((hotfix|bugfix|feature)/[a-zA-Z0-9\-]+)$'

message="Invalid branch name. Use one of: feature/, bugfix/, hotfix/. Example: feature/add-login-page"

if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
  echo "\033[0;31m$message"
  exit 1
fi

exit 0
